apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress-wordpress
  namespace: wordpress
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/proxy-body-size: "500m"
spec:
  rules:
  - host: blog.192.168.0.242.nip.io
    http:
      paths:
      - backend:
          serviceName: wordpress
          servicePort: 8081
