apiVersion: v1
kind: Service
metadata:
  labels:
    name: wordpress
  name: wordpress
  namespace: wordpress
spec:
  type: NodePort
  ports:
    - nodePort: 31689
      port: 80
      protocol: TCP
      targetPort: 80
  selector:
    app: wordpress
